r-lib/clock

R/duration.R, R/time-point.R, man/duration-arithmetic.Rd, man/duration-helper.Rd, man/duration-rounding.Rd, src/duration.cpp, tests/testthat/_snaps/duration.md, tests/testthat/_snaps/time-point.md, tests/testthat/test-duration.R, tests/testthat/test-time-point.R
Closes #122 
Calendrical - year, quarter, month
Chronological - day, hour, minute, second, millisecond, microsecond, nanosecond
This allows for a much clearer picture of how durations interact with calendars and time points.
We lose the ability to do `duration<year> + duration<second>`, but that isn't a huge deal because it is normally confusing. If you really want this, you can do `duration_cast(duration<year>, "second") + duration<second>`.
`duration_cast()` is now the only function that can convert across the calendrical/chronological border.
=> Separate durations into calendrical and chronological

inst/include/date/date.h, src/parse.h, src/tz.cpp, tools/update, tools/update-date-library.R
Closes #146 
One of the date.h changes updated `read_long_double()` (used for reading seconds / fractional seconds). It no longer uses `strtold()`, and instead parses this in a custom way that is a good bit faster. I've incorporated these into our custom `read_seconds()`.
A simple test showed reading 1e6 second precision strings in 550ms, when it used to take 700ms. The same amount of nanosecond precision strings now read in 800ms when it used to take 1000ms.
=> Update embedded date library

inst/include/date/date.h, tests/testthat/test-gregorian-year-month-day.R
Note that this is a change to date.h directly
The standard recommends passing unsigned char to `toupper()`, as passing a char that might be negative would result in undefined behavior. This is exactly what was happening to us when using a non-English locale.
Notes section of https://en.cppreference.com/w/cpp/string/byte/toupper
https://stackoverflow.com/questions/21805674/do-i-need-to-cast-to-unsigned-char-before-calling-toupper-tolower-et-al
=> Cast to `unsigned char` before calling `toupper()`

src/gregorian-year-month-day.cpp, src/locale.h, src/parse.h, src/time-point.cpp, src/zoned-time.cpp, tests/testthat/test-clock-labels.R, tests/testthat/test-gregorian-year-month-day.R, tests/testthat/test-naive-time.R, tests/testthat/test-zoned-time.R
Negligible performance impact, which is good
``` r
library(clock)
x <- rep("2019-01-01", 1e6)
bench::mark(year_month_day_parse(x), iterations = 10)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression                   min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>              <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 year_month_day_parse(x)    387ms    396ms      2.45      12MB     3.92
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression                   min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>              <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 year_month_day_parse(x)    386ms    391ms      2.46 …
```
=> Ensure input, labels, and format are all in UTF-8 when parsing

R/date.R, tests/testthat/test-date.R
Closes #191 
We are generally a bit more lax with Dates and POSIXct. For POSIXct, we already floor to get rid of fractional seconds, so this just adds similar behavior for Dates and fractional days.
=> Floor double Dates before casting to integer with `duration_days()`

NEWS.md, src/duration.cpp
Since calling `pow(int, int)` is undefined on that platform and results in:
```cpp
duration.cpp:1143:87: error: call of overloaded ‘pow(int, int)’ is ambiguous
static int64_t DOUBLE_MAX_NO_LOSS = static_cast<int64_t>(pow(FLT_RADIX, DBL_MANT_DIG) - 1);
^
In file included from /usr/include/math.h:15:0,
from /opt/csw/include/c++/5.2.0/cmath:44,
from /opt/csw/include/c++/5.2.0/random:38,
from /opt/csw/include/c++/5.2.0/bits/stl_algo.h:66,
from /opt/csw/include/c++/5.2.0/algorithm:62,
from ../inst/include/date/date.h:44,
from clock.h:5,
from duration.cpp:1:
/opt/csw/lib/gcc/i386-pc-solaris2.10/5.2.0/include-fixed/iso/math_iso.h:204:21: note: candidate: long double std::pow(long double, long double)
inline long double pow(long double __X, long double __Y) { return
^ …
```
=> Pass `double`s to `pow()` for Solaris

NEWS.md, R/utils.R, tests/testthat/_snaps/date.md, tests/testthat/_snaps/gregorian-year-day.md, tests/testthat/_snaps/gregorian-year-month-day.md, tests/testthat/_snaps/naive-time.md, tests/testthat/_snaps/posixt.md
=> Use error bullets for `nonexistent`, `ambiguous`, and `invalid` errors

NEWS.md, R/utils.R, src/failure.h, src/format.cpp, src/gregorian-year-month-day.cpp, src/parse.h, src/time-point.cpp, src/zoned-time.cpp, tests/testthat/_snaps/date.md, tests/testthat/_snaps/naive-time.md, tests/testthat/test-date.R, tests/testthat/test-naive-time.R
=> Generate warnings when formatting naive-times with `%Z` or `%z`

R/date.R, R/posixt.R, man/date-time-parse.Rd, man/date_parse.Rd, tests/testthat/test-date.R, tests/testthat/test-gregorian-year-month-day.R, tests/testthat/test-naive-time.R, tests/testthat/test-zoned-time.R
=> Document and test rounding that can occur when parsing

NEWS.md, R/date.R, R/gregorian-year-month-day.R, R/naive-time.R, R/posixt.R, R/sys-time.R, R/zoned-time.R, man/date-time-parse.Rd, man/date_parse.Rd, man/naive_time_parse.Rd, man/sys_time_parse.Rd, man/year_month_day_parse.Rd, man/zoned-parsing.Rd, tests/testthat/test-date.R, tests/testthat/test-naive-time.R, tests/testthat/test-zoned-time.R
Closes #230 
It turns out this was not actually a date bug. I misunderstood how `%NS` was supposed to work. Really this is only useful for cases where you need to parse seconds that might have more than one leading zero, like `007`. It should be extremely rare to ever use `N`. I have completely redocumented how that is supposed to work.
date considers parsing a string with fractional seconds into a coarser time point, like one with second precision, to be unsupported behavior (a similar argument is made when parsing a string with hours into a day precision time point). I was unaware of this, and thought that `%NS` was used for this exact case, which is not true. Instead _you should use a precision that is at least as precise as the string you are parsing_. So a string with milliseconds …
=> More correctly document `%NS` and invalid coarse parsing behavior

NEWS.md, tests/testthat/test-date.R, tests/testthat/test-gregorian-year-month-day.R, tests/testthat/test-naive-time.R, tests/testthat/test-utils.R, tests/testthat/test-zoned-time.R
We are planning a breaking change to the condition expectations in testthat release (see NEWS item in https://github.com/r-lib/testthat/pull/1401). This PR implements a preventive fix that works with and without the breaking change.
There is no hurry to get this fix on CRAN since we are skipping one released version of testthat before going through with the change.
=> Fix condition expectations in prevision of testthat breaking change

NEWS.md, R/cpp11.R, R/duration.R, src/cpp11.cpp, src/duration.cpp, tests/testthat/_snaps/duration.md, tests/testthat/test-duration.R
We will need this for #266 for computing the time point differences. In most cases of the high level API, this should never have OOB issues, but it can if you use a finer precision like nanoseconds. For now that is okay, we can come back to this later and make a variant return a 64 bit integer type if we need to
=> Implement `<duration> %/% <duration>`

R/calendar.R, R/date.R, R/gregorian-year-day.R, R/gregorian-year-month-day.R, R/gregorian-year-month-weekday.R, R/iso-year-week-day.R, R/posixt.R, R/quarterly-year-quarter-day.R, man/date-count-between.Rd, man/posixt-count-between.Rd, man/year-month-day-count-between.Rd, man/year-month-weekday-count-between.Rd, tests/testthat/_snaps/calendar.md, tests/testthat/_snaps/date.md, tests/testthat/_snaps/gregorian-year-month-day.md, tests/testthat/_snaps/gregorian-year-month-weekday.md, tests/testthat/_snaps/posixt.md, tests/testthat/test-calendar.R, tests/testthat/test-date.R, tests/testthat/test-gregorian-year-month-day.R, tests/testthat/test-gregorian-year-month-weekday.R, tests/testthat/test-posixt.R
Closes #270 
Rationale described in https://github.com/r-lib/clock/issues/270#issuecomment-984053954
=> Allow `"quarter"` in `calendar_count_between()` for `<year_month_*>`

NEWS.md, R/naive-time.R, R/posixt.R, R/sys-time.R, tests/testthat/test-posixt.R
Closes #278 
This ensures we go through promotion to at least second precision by utilizing the existing `as_zoned_time()` method for sys-time, which already does that.
=> Use more correct coercion path from sys-time to POSIXct

NEWS.md, R/date.R, R/duration.R, R/posixt.R, man/date-sequence.Rd, man/date_seq.Rd, man/posixt-sequence.Rd, man/seq.clock_duration.Rd, man/seq.clock_iso_year_week_day.Rd, man/seq.clock_time_point.Rd, man/seq.clock_year_day.Rd, man/seq.clock_year_month_day.Rd, man/seq.clock_year_month_weekday.Rd, man/seq.clock_year_quarter_day.Rd, src/duration.cpp, src/utils.h, tests/testthat/_snaps/duration.md, tests/testthat/test-date.R, tests/testthat/test-duration.R, tests/testthat/test-posixt.R
Closes #282 
Also improves on potential overflow issues
=> Allow `from > to` when `by > 0` in `seq()` methods

NEWS.md, tests/testthat/_snaps/date.md, tests/testthat/_snaps/posixt.md, tests/testthat/helper-format.R, tests/testthat/test-date.R, tests/testthat/test-posixt.R
Instead, we now just print them out normally, which hopefully will work
Follow up to #285
=> Don't use `cat()` for formatting tests that may involve UTF-8

DESCRIPTION, NEWS.md, R/rcrd.R, R/utils.R, R/weekday.R, tests/testthat/_snaps/calendar.md, tests/testthat/_snaps/date.md, tests/testthat/_snaps/naive-time.md, tests/testthat/_snaps/posixt.md, tests/testthat/_snaps/sys-time.md, tests/testthat/_snaps/time-point.md
* Eliminates `devtools::test()` WARNINGs and ERRORs
* `vec_equal_na()` was deprecated in {vctrs} v0.5.0 so use `vec_detect_missing()` instead
* Update all snapshots to match current output
=> fix: Unit tests

DESCRIPTION, NEWS.md, R/date.R, R/posixt.R, R/zzz.R, tests/testthat/_snaps/date.md, tests/testthat/_snaps/posixt.md, tests/testthat/test-date.R, tests/testthat/test-posixt.R
Joint PR with https://github.com/DavisVaughan/slider/pull/184
``` r
library(clock)
library(slider)
i <- date_build(2019, 1, c(1, 3, 4, 5, 7, 8))
slide_index(i, i, identity, .before = duration_days(2))
#> [[1]]
#> [1] "2019-01-01"
#> 
#> [[2]]
#> [1] "2019-01-01" "2019-01-03"
#> 
#> [[3]]
#> [1] "2019-01-03" "2019-01-04"
#> 
#> [[4]]
#> [1] "2019-01-03" "2019-01-04" "2019-01-05"
#> 
#> [[5]]
#> [1] "2019-01-05" "2019-01-07"
#> 
#> [[6]]
#> [1] "2019-01-07" "2019-01-08"
```
<sup>Created on 2022-11-10 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>
=> Lazily register `slider_plus()` and `slider_minus()` methods

NEWS.md, tests/testthat/test-posixt.R
Closes #312 
In particular see https://github.com/r-lib/clock/issues/312#issuecomment-1507528450
=> Skip problematic test on 32-bit architectures

src/integers.h
To manage the protection of it, important when `rclock::integers` are being created from "on the fly" vectors
This will be important for some upcoming PRs related to streamlining the calendar code
---
The current approach is honestly a memory protection issue, because you can create a `rclock::integers` from something that can go out of scope before the `rclock::integers` class does.
=> Take ownership of the read-only data

NEWS.md, R/cpp11.R, R/date.R, R/duration.R, src/calendar.h, src/cpp11.cpp, src/doubles.h, src/duration.cpp, src/duration.h, src/format.cpp, src/get.h, src/gregorian-year-day.cpp, src/gregorian-year-month-day.cpp, src/gregorian-year-month-weekday.cpp, src/iso-year-week-day.cpp, src/naive-time.cpp, src/quarterly-year-quarter-day.cpp, src/rcrd.cpp, src/sys-time.cpp, src/time-point.cpp, src/weekday.cpp, src/zoned-time.cpp, tests/testthat/_snaps/duration.md, tests/testthat/test-duration.R
Part of #280 
#280 is still a little complicated with sys-time, naive-time, and zoned-time. We can now represent the full range of an `int64_t` in these types, but they don't _print_ correctly because the print method used by date forces them through `year_month_day`, which has a year limit of +/-32767. 
Essentially, the _true_ range supported by time points and calendar types in date is the lower bound of what is supported by:
- `year_month_day`
- The time point type at a given `precision`
See `Range of validity` here which also outlines this, giving the following limits (on that particular computer):
https://howardhinnant.github.io/date/date.html#range
```
picoseconds range is     : [1969-09-16 05:57:07.963145224192, 1970-04-17 18:02:52.036854775807]
nanoseconds range is     : …
```
=> Rework durations and time points on top of 2 double vectors

NEWS.md, R/calendar.R, R/date.R, R/duration.R, R/gregorian-year-day.R, R/gregorian-year-month-day.R, R/gregorian-year-month-weekday.R, R/iso-year-week-day.R, R/naive-time.R, R/posixt.R, R/quarterly-year-quarter-day.R, R/sys-time.R, R/time-point.R, R/week-year-week-day.R, R/weekday.R, R/zoned-time.R, man/as_date.Rd, man/as_duration.Rd, man/as_iso_year_week_day.Rd, man/as_naive_time.Rd, man/as_sys_time.Rd, man/as_weekday.Rd, man/as_year_day.Rd, man/as_year_month_day.Rd, man/as_year_month_weekday.Rd
Closes #348
Currently these are the only clock generics that I am super happy with as being fully extensible
=> Add `...` to all `as_*()` generics

NEWS.md, src/quarterly.h
They are disallowed here in C++20, which is enforced by new versions of gcc (14.1.0 and up)
From CRAN
```
Found the following significant warnings:
quarterly.h:203:12: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
quarterly.h:204:31: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
quarterly.h:258:23: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
quarterly.h:259:33: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
quarterly.h:371:39: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
quarterly.h:372:49: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
quarterly.h:374:49: warning: template-id not …
```
=> Remove `<S>` in quarterly constructors

NEWS.md, src/quarterly-shim.h, src/week-shim.h
Closes https://github.com/r-lib/clock/issues/357
This function was an issue because we used it in `constexpr` contexts
```cpp
static
inline
void
never_reached [[noreturn]] () {
// Compiler hint to allow [[noreturn]] attribute. This is never executed since
// `never_reached()` is never actually called.
throw std::runtime_error("[[noreturn]]");
}
```
We are forced to throw in the unreachable `default` cases of our switch statements due to the fact that you can convert _anything_ to an enum and have it go through the switch statement, even though that doesn't happen in practice.
The `throw` is actually ok in `constexpr` and `noexcept` contexts because it represents an ill-formed function and will completely abort the program (the `noexcept` in particular turns the `throw` into a …
=> Use constructor defaults to fix `constexpr` issues

NEWS.md, src/ordinal.h, src/week.h
The space after `""` is deprecated since it creates ambiguity with reserved `_`-initial names per:
https://en.cppreference.com/w/cpp/language/user_literal
=> Fix 'operator"" ' whitespace issue

src/parse.h
With two's complement you can't invert the min value with `-`
Found as part of CRAN's clang20-ubsan checks (note the test failures themselves are unrelated and have been fixed elsewhere), here we are interested in the:
```
negation of -9223372036854775808 cannot be represented in type 'rep' (aka 'long'); cast to an unsigned type to negate this value to itself
```
My guess is that this is the test that triggered it (the `-` parses, so `neg` is set, but `0a:00` doesn't parse, so `toff` is left as `not_a_offset`)
```r
test_that("%z must parse correctly if included", {
expect <- as_zoned_time(sys_days(NA), "America/New_York")
x <- "1970-01-01 00:00:00-0a:00 EST"
expect_warning(
result <- zoned_time_parse_abbrev(
x,
"America/New_York",
format = "%Y-%m-%d %H:%M:%S%Ez %Z"
)
) …
```
=> Avoid inverting `not_a_offset`, which is `minutes::min()` i.e. min of `long`
